#---------------------------------------------------------------------
# GitHub Action Workflow Basics
# Version      Date        Info
# 1.0          2019        Initial Version
# Made by .. ..  Copyright (c) 2048
#---------------------------------------------------------------------
name: my_project01
env:
  APPLICATION_NAME    : "MyFlaskApp"
  DEPLOY_PACKAGE_NAME : "flask-app-ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - main

jobs:
  my_testing:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Git clone our repository
        uses: actions/checkout@v1
        
      - name: Execute few commands
        run : |
          echo "Printing Global ENV variable ${{ env.DEPLOY_PACKAGE_NAME }}"
          ls -la  

  my_deploy:
    runs-on: [ubuntu-latest]
    needs: [my_testing]      
    env:
      VAR1 : "Job Variable 1"
      VAR2 : "Job Variable 2"
    
    steps:
      - name: Printing some more info
        run : |
          echo "Hello World from Deploy"
          echo "App name is ${{ env.APPLICATION_NAME }}"
          echo "Var1 = ${{ env.VAR1 }}"
          echo "Var2 = ${{ env.VAR2 }}"
          echo "Var3 = $LOCAL_VAR1"
          ls -la
          aws --version
          zip --version
      
      - name: Print super local env var
        run : echo "This is local variable $LOCAL_VAR1"
        env :
          LOCAL_VAR1 : "Hello Iam local Variable"

        
